"""Initial migration

Revision ID: 376e7c4910ad
Revises: 
Create Date: 2025-05-01 21:20:05.473787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376e7c4910ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('rated', sa.String(length=10), nullable=True),
    sa.Column('released', sa.String(length=20), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('writer', sa.String(length=200), nullable=True),
    sa.Column('actors', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('rt_rating', sa.String(length=10), nullable=True),
    sa.Column('metascore', sa.Integer(), nullable=True),
    sa.Column('box_office', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_user_friends_friend_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_friends_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('user_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='fk_user_movie_movie_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_movie_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='_user_movie_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie')
    op.drop_table('user_friends')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
