"""adding poster url

Revision ID: 61035a638697
Revises: 376e7c4910ad
Create Date: 2025-05-08 10:12:41.529932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61035a638697'
down_revision = '376e7c4910ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
